image: docker:latest

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/pagameba/node-test-app:latest .
    - docker push registry.gitlab.com/pagameba/node-test-app:latest